### ISSUE TITLE
`recover` fails if .backup file doesn't exist

### ISSUE THREAD

**Issue by RobertOdrowaz** [kwertop/persistent-node-cache#1]
`recover` fails if the .backup file doesn't exist, with an error Error: ENOENT: no such file or directory, open '{path}.backup'. This can occur when the server restarts before the first backup. With the default 1s backup interval, this probably will never happen, but with a longer interval, it definitely can. I guess this can be solved by either handling the missing .backup file during recover or by creating an empty file on the first start, as is the case for .append.

By the way, great package! It's exactly what I needed, and I'm surprised it's not more popular

**Comment by kwertop** [comment]
@RobertOdrowaz Thanks for highlighting the issue. Will be fixed in next release.

> By the way, great package! It's exactly what I needed, and I'm surprised it's not more popular
🙂 . Awesome. Spread the word.

**Comment by kwertop** [comment]
This issue is fixed in https://github.com/kwertop/persistent-node-cache/commit/33dfde4963744ba0528033175fc726ad7ec22285
